services:
  consul:
    image: hashicorp/consul:latest
    container_name: payd-consul
    restart: unless-stopped
    ports:
      - 9090:8500
    volumes:
      - ./consul/data:/consul/data
      - ./consul/config:/consul/config
    networks:
      - payd-net

  consul-init:
    image: curlimages/curl
    container_name: payd-consul-init
    volumes:
      - ./consul/init.sh:/init.sh
      - ./consul/config:/consul/config
    command: /init.sh
    depends_on:
      consul:
        condition: service_started
    networks:
      - payd-net

  prometheus:
    image: prom/prometheus
    container_name: payd-prometheus
    restart: unless-stopped
    ports:
      - 9091:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - payd-net

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: payd-jaeger
    restart: unless-stopped
    ports:
      - 14268:14268
      - 16686:16686
    networks:
      - payd-net

  database:
    image: postgres
    container_name: payd-db
    restart: unless-stopped
    ports:
      - 5442:5432
    environment:
      - POSTGRES_DB=payd
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./database/data:/var/lib/postgresql/data
    #healthcheck:
    #  test: ["CMD-SHELL", "pg_isready -U liquibase -d liquibase_migration"]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5
    networks:
      - payd-net

  liquibase:
    image: liquibase/liquibase:latest
    container_name: payd-migration
    #depends_on:
    #  database:
    #    condition: service_healthy 
    command: --defaults-file=/liquibase/liquibase.properties update
    volumes:
      - ./database/liquibase.properties:/liquibase/liquibase.properties
      - ./database/migration:/liquibase/changelog
    networks:
      - payd-net

networks:
  payd-net:
    driver: bridge