app:
    name: "RMS API Dev"

otel:
    host: "localhost"
    port: 4318

database:
    url: "localhost"
    port: 5442
    name: "payd"
    ssl: "disable"
    username: "admin"
    password: "admin"
